In [3]:
import os
import sys

print("현재 작업 위치:", os.getcwd())
print("Python 실행 위치:", sys.executable)

현재 작업 위치: /home/yongbin/projects/rna-seq-variant-portfolio/human_lps/notebooks
Python 실행 위치: /home/yongbin/projects/rna-seq-variant-portfolio/human_lps/.venv/bin/python

In [4]:
import glob

count_files = sorted(glob.glob("../results/counts/*.counts.txt"))

print("count 파일 개수:", len(count_files))
for f in count_files:
    print(f)

count 파일 개수: 6
../results/counts/SRR11994200.counts.txt
../results/counts/SRR11994201.counts.txt
../results/counts/SRR11994202.counts.txt
../results/counts/SRR11994203.counts.txt
../results/counts/SRR11994204.counts.txt
../results/counts/SRR11994205.counts.txt

In [5]:
import pandas as pd

test_df = pd.read_csv(count_files[0], sep="\t", comment="#")
test_df.head()

,Geneid,Chr,Start,End,Strand,Length,/home/yongbin/projects/rna-seq-variant-portfolio/human_lps/results/bam/SRR11994200.sorted.bam
0,ENSG00000279928,1;1;1;1;1,182696;183132;183494;183740;183981,182746;183216;183571;183901;184174,+;+;+;+;+,570,1
1,ENSG00000228037,1;1;1,2581560;2583370;2584125,2581650;2583495;2584533,+;+;+,626,12
2,ENSG00000142611,1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;...,3069168;3069183;3069197;3069203;3069211;318612...,3069296;3069296;3069296;3069296;3069296;318647...,+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;...,9767,4
3,ENSG00000284616,1;1;1;1,5301928;5303328;5304401;5306942,5302004;5303393;5305029;5307394,-;-;-;-,1225,0
4,ENSG00000157911,1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;...,2403964;2403974;2404061;2404613;2404838;240503...,2405834;2405834;2404371;2404891;2405828;240583...,-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;...,3782,92

In [6]:
import os
import pandas as pd

dfs = []

for file in count_files:
    sample_name = os.path.basename(file).replace(".counts.txt", "")
    
    df = pd.read_csv(file, sep="\t", comment="#")
    df = df[["Geneid", df.columns[-1]]]
    df.columns = ["Geneid", sample_name]
    
    dfs.append(df)

count_matrix = dfs[0]

for df in dfs[1:]:
    count_matrix = count_matrix.merge(df, on="Geneid")

count_matrix.head()

,Geneid,SRR11994200,SRR11994201,SRR11994202,SRR11994203,SRR11994204,SRR11994205
0,ENSG00000279928,1,4,0,1,0,3
1,ENSG00000228037,12,12,85,34,30,11
2,ENSG00000142611,4,0,2,4,0,3
3,ENSG00000284616,0,0,0,0,0,0
4,ENSG00000157911,92,207,105,187,69,189

In [7]:
count_matrix.shape

(62754, 7)

In [8]:
output_path = "../results/count_matrix.csv"

count_matrix.to_csv(output_path, index=False)

print("저장 완료:", output_path)

저장 완료: ../results/count_matrix.csv

In [9]:
check_df = pd.read_csv("../results/count_matrix.csv")
check_df.head()

,Geneid,SRR11994200,SRR11994201,SRR11994202,SRR11994203,SRR11994204,SRR11994205
0,ENSG00000279928,1,4,0,1,0,3
1,ENSG00000228037,12,12,85,34,30,11
2,ENSG00000142611,4,0,2,4,0,3
3,ENSG00000284616,0,0,0,0,0,0
4,ENSG00000157911,92,207,105,187,69,189

In [10]:
import pandas as pd

metadata = pd.DataFrame({
"sample": [
"SRR11994200",
"SRR11994201",
"SRR11994202",
"SRR11994203",
"SRR11994204",
"SRR11994205"
],
"condition": [
"Control",
"Control",
"Control",
"LPS",
"LPS",
"LPS"
]
})

metadata

        sample condition
0  SRR11994200   Control
1  SRR11994201   Control
2  SRR11994202   Control
3  SRR11994203       LPS
4  SRR11994204       LPS
5  SRR11994205       LPS

In [11]:
count_matrix.columns

Index(['Geneid', 'SRR11994200', 'SRR11994201', 'SRR11994202', 'SRR11994203',
       'SRR11994204', 'SRR11994205'],
      dtype='str')

In [12]:
metadata.to_csv("../metadata/sample_metadata.csv", index=False)

In [13]:
check_meta = pd.read_csv("../metadata/sample_metadata.csv")
check_meta

        sample condition
0  SRR11994200   Control
1  SRR11994201   Control
2  SRR11994202   Control
3  SRR11994203       LPS
4  SRR11994204       LPS
5  SRR11994205       LPS

In [1]:
import os
os.getcwd()

'/home/yongbin/projects/rna-seq-variant-portfolio/human_lps/notebooks'

In [2]:
import pandas as pd

count_matrix = pd.read_csv("../results/count_matrix.csv")
metadata = pd.read_csv("../metadata/sample_metadata.csv")

display(count_matrix.head())
display(metadata)

print("count_matrix shape:", count_matrix.shape)
print("metadata shape:", metadata.shape)

,Geneid,SRR11994200,SRR11994201,SRR11994202,SRR11994203,SRR11994204,SRR11994205
0,ENSG00000279928,1,4,0,1,0,3
1,ENSG00000228037,12,12,85,34,30,11
2,ENSG00000142611,4,0,2,4,0,3
3,ENSG00000284616,0,0,0,0,0,0
4,ENSG00000157911,92,207,105,187,69,189

        sample condition
0  SRR11994200   Control
1  SRR11994201   Control
2  SRR11994202   Control
3  SRR11994203       LPS
4  SRR11994204       LPS
5  SRR11994205       LPS

count_matrix shape: (62754, 7)
metadata shape: (6, 2)